development: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: schedule_ufma_grajau_development
  username: postgres
  password:
  host: localhost

test:
  <<: *default
  database: schedule_ufma_grajau_test

production:
  url: <%= ENV['DATABASE_URL'] %>
